- hosts: webserver
  remote_user: ubuntu
  become: true
  become_method: sudo

  vars_files:
    - vars.yml

  tasks:
  - name: "Checkout"
      git: repo={{repository_url}} dest={{repository_url}} version={{repository_branch}}
