- hosts: webserver
  remote_user: ubuntu
  become: true
  become_method: sudo

  vars_files:
    - vars.yml

  tasks:
  - git:
      repo: https://github.com/zola-octanoviar/api-chatbot.git
      dest: /home/ubuntu/api-chatbot/
      force: yes

  - name: sync  from git to folder
    command: mv /home/ubuntu/api-chatbot/ /var/www/html/api-chatbot/

#  - name: sync  from git to folder
#    synchronize:
#      src: /home/ubuntu/api-chatbot/
#      dest: /var/www/html/api-chatbot/
#      delegate_to: webserver
