- hosts: ec2-18-206-57-23.compute-1.amazonaws.com
  remote_user: ubuntu
  become: true
  become_method: sudo

  vars_files:
    - vars.yml

  tasks:
    - name: "set system time to local time if not yet set"
      timezone:
        name: Asia/Jakarta

    - name: "install common packages"
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: true
      with_items:
        - htop
        - python-pip

    - name: "install required postgresql packages"
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: true
      with_items:
        - postgresql

    - name: "install dependency to run postgresql_db"
      pip:
        name: "{{ item }}"
      with_items:
        - psycopg2
        - pgcli


